name: Android Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ANDROID_SDK_ROOT: /usr/local/android-sdk

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install KVM
        run: sudo apt-get update && sudo apt-get install -y cpu-checker && egrep -c '(vmx|svm)' /proc/cpuinfo

      - name: Verify KVM support
        run: kvm-ok

      - name: Install Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-6858069_latest.zip -d $ANDROID_SDK_ROOT
          echo "export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "export PATH=\$PATH:\$ANDROID_SDK_ROOT/cmdline-tools/bin:\$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_ENV 

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Set up virtual display
        run: sudo apt-get install -y xvfb

      - name: Start virtual display
        run: Xvfb :1 -screen 0 1280x720x24 > /dev/null 2>&1 &

      - name: Set display environment variable
        run: export DISPLAY=:1

      - name: Lint
        run: |
          chmod +x ./gradlew
          ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

      - name: Build
        run: ./gradlew assembleDebug

      - name: Run Test
        run: ./gradlew -Pci --console=plain :app:testDebug

      - name: Start emulator
        run: |
          avdmanager create avd -n test_emulator -k "system-images;android-30;google_apis;x86_64" --device "Nexus 6P" --sdcard 128M --force
          emulator -avd test_emulator -no-window -no-audio &

      - name: Wait for emulator to start
        run: android-wait-for-emulator

      - name: Build and run tests
        run: |
          ./gradlew connectedAndroidTest

